import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {Worker} from 'node:worker_threads';
import {once} from 'node:events';
import {createInboxStorage,cloneInboxMetadata} from './erp-inbox-storage.mjs';

const directory=await fs.mkdtemp(path.join(os.tmpdir(),'erp-storage-reuse-'));
const file=path.join(directory,'inbox.json'),envelope={batch:{rows:[{evidence:'immutable-'.repeat(100000)}]}};
const original=Worker.prototype.postMessage,transfers=[];
let worker;
Worker.prototype.postMessage=function(message,...args){worker=this;transfers.push({action:message.action,bytes:JSON.stringify(message).length,additions:message.additions?.length});return original.call(this,message,...args);};
try {
  await fs.writeFile(file,JSON.stringify([{kind:'batch',status:'pending',envelope}]));
  const storage=createInboxStorage(file);
  let records=cloneInboxMetadata(await storage.read());
  assert.ok(Object.isFrozen(records[0].envelope.batch.rows[0]));
  records[0].status='acknowledged';await storage.write(records);
  assert.equal(transfers.at(-1).additions,0,'existing evidence stays in its storage worker');
  assert.ok(transfers.at(-1).bytes<1000,'metadata writes do not transfer historical evidence');
  assert.deepEqual(JSON.parse(await fs.readFile(file,'utf8'))[0].envelope,envelope);
  const before=await fs.stat(file),count=transfers.length;
  await storage.write(cloneInboxMetadata(await storage.read()));
  assert.equal((await fs.stat(file)).mtimeMs,before.mtimeMs,'idempotent writes leave the durable file untouched');
  assert.equal(transfers.length,count);
  records=cloneInboxMetadata(await storage.read());
  records.push({kind:'batch',status:'pending',envelope:{batch:{rows:[{sku:'new',unitCost:0}]}}});
  await storage.write(records);assert.equal(transfers.at(-1).additions,1,'new evidence transfers once');
  const committed=JSON.parse(await fs.readFile(file,'utf8'));
  assert.deepEqual(committed,records);
  const exited=once(worker,'exit');await worker.terminate();await exited;
  records=cloneInboxMetadata(await storage.read());records[1].status='acknowledged';
  await storage.write(records);
  assert.deepEqual(JSON.parse(await fs.readFile(file,'utf8')),records,'replacement worker recovers all evidence before committing');
  await fs.writeFile(file,JSON.stringify([{kind:'batch',status:'pending',envelope:{external:true}}]));
  const replaced=await storage.read();assert.equal(replaced[0].envelope.external,true);
  const replacement=cloneInboxMetadata(replaced);replacement[0].status='acknowledged';await storage.write(replacement);
  assert.deepEqual(JSON.parse(await fs.readFile(file,'utf8')),replacement,'external replacement cannot use old evidence references');
  console.log('ERP persistent storage worker: metadata-only transfer, immutable/new evidence, no-op, worker recovery and external replacement passed');
}finally{Worker.prototype.postMessage=original;await worker?.terminate();await fs.rm(directory,{recursive:true,force:true});}
